-- CreateTable
CREATE TABLE `pso` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `COS` VARCHAR(191) NOT NULL,
    `CO1` INTEGER NOT NULL,
    `CO2` INTEGER NOT NULL,
    `CO3` INTEGER NOT NULL,
    `CO4` INTEGER NOT NULL,
    `CO5` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
